avalanche:
  extraArgs:
    - --api-admin-enabled=true

  resources:
    limits:
      cpu: 4
      memory: 20Gi

  p2pNodePort:
    enabled: true
    port: 31700 # Must be globally unique and available on the host

  extraLabels:
    app.kubernetes.io/workload-type: blockchain-stateful
    app.kubernetes.io/blockchain: avalanche-mainnet

  affinityPresets:
    antiAffinityByHostname: false

prometheus:
  serviceMonitors:
    enabled: true

grafana:
  dashboards: true

configTemplate: |
    snowman-api-enabled = "false"
    eth-apis = [
      "admin",
      "eth",
      "eth-filter",
      "net",
      "web3",
      "internal-eth",
      "internal-blockchain",
      "internal-transaction",
      "internal-tx-pool",
      "internal-account"
    ]
    metrics-enabled = "true"
    pruning-enabled = "false"
    state-sync-enabled = "false"