# Copy this file to helmfile.yaml and customise it for your needs

bases:
  - ./helmfile.common.yaml

helmfiles:
  - path: namespaces/storage.yaml
  - path: namespaces/sealed-secrets.yaml
  - path: namespaces/postgres-operator.yaml
  - path: namespaces/ingress.yaml
  - path: namespaces/monitoring.yaml
  - path: namespaces/eth-sepolia.yaml
  - path: namespaces/eth-mainnet.yaml
  - path: namespaces/arbitrum-one.yaml
  - path: namespaces/graph-arbitrum-sepolia.yaml
