# yaml-language-server: $schema=file:///home/cjw.graphops/code/graphops/upstream/launchpad-namespaces-upd/schema.json

bases:
  - ./helmfile.common.yaml

repositories:
- name: strimzi
  url: https://strimzi.io/charts/
- name: graphops
  url: https://graphops.github.io/launchpad-charts

helmfiles:
  - path: namespaces/storage.yaml
  - path: namespaces/sealed-secrets.yaml
  - path: namespaces/postgres-operator.yaml
  - path: namespaces/ingress.yaml
  - path: namespaces/monitoring.yaml
  - path: namespaces/eth-sepolia.yaml
  - path: namespaces/eth-mainnet.yaml
