statefulNode:
  extraArgs:
    - --chain=bor-mainnet
    - --bor.heimdall=https://heimdall-polygon-mainnet-0-heimdall:1317
    - --torrent.download.rate=100mb # Download snapshot files faster
    - --torrent.download.slots=6 # 3 is default
    - --db.read.concurrency=16 # Does limit amount of parallel db reads. Default: equal to GOMAXPROCS (or number of CPU) (default: 10)
    - --http.corsdomain=*
    - --ws # enable ws
    - --http.api=eth,debug,net,trace
    - --trace.maxtraces=10000
    - --externalcl

  restoreSnapshot:
    enable: true
    snapshotUrl: https://matic-blockchain-snapshots.s3-accelerate.amazonaws.com/matic-mainnet/erigon-archive-snapshot-2022-12-13.tar.gz

  p2pNodePort:
    enabled: true
    port: 31400 # Must be globally unique and available on the host

rpcdaemon:
  enabled: true
  replicaCount: 1 # scale me
  extraArgs:
    - --http.api=eth,debug,net,trace
    - --trace.maxtraces=10000
    - --http.corsdomain=*
    - --ws # enable ws