# tasks that involve preparing and managing hosts
version: '3'

vars:
  INVENTORY_PATH: '{{.INVENTORY_PATH | default "inventory/inventory.yaml"}}'

tasks:
  apply-base:
    interactive: true
    desc: Performs base host configuration, including package installations, configuring SSH and zfs setup if applicable
    cmds:
      - ansible-playbook -vv launchpad-core/ansible/site.yaml -i {{.INVENTORY_PATH}} {{.CLI_ARGS}}

  apply-k0s:
    interactive: true # for interactive scripts
    desc: Joins all hosts into a K0s cluster as defined in the inventory
    cmds:
      - ansible-playbook -vv launchpad-core/ansible/install_k0s_cluster.yaml --diff -i {{.INVENTORY_PATH}} {{.CLI_ARGS}}

  upgrade-k0s-node:
    interactive: true # for interactive scripts
    desc: Playbook to upgrade version of k0s on one cluster node at a time
    cmds:
      - ansible-playbook -vv launchpad-core/ansible/upgrade.yaml --diff -i {{.INVENTORY_PATH}} {{.CLI_ARGS}}

  # k0s-sysinfo: # TODO add task for running k0s sysinfo on a host/hosts
