# Values file for https://github.com/graphops/helm-charts/tree/main/charts/resource-injector

resources:
  postgres-cr-primary-subgraph-data:
    apiVersion: "acid.zalan.do/v1"
    kind: postgresql
    metadata:
      name: pg-primary-subgraph-data
    spec:
      teamId: "pg"
      numberOfInstances: 1
      users:
        graph:
          - superuser
      enableMasterLoadBalancer: false
      enableReplicaLoadBalancer: false
      enableConnectionPooler: false # enable/disable connection pooler deployment
      enableReplicaConnectionPooler: false # set to enable connectionPooler for replica service
      databases:
        graph: graph
      postgresql:
        version: "14"
        parameters: {}
      volume:
        size: 500Gi
        storageClass: openebs-rawfile-localpv # change me to your desired storage class
      resources:
        requests:
          cpu: 500m
          memory: 4Gi
        limits:
          cpu: 4000m
          memory: 16Gi
      patroni:
        initdb:
          encoding: "UTF8"
          locale: "C" # Improves performance and important for determinism
  postgres-cr-indexer-metadata:
    apiVersion: "acid.zalan.do/v1"
    kind: postgresql
    metadata:
      name: pg-indexer-metadata
    spec:
      teamId: "pg"
      numberOfInstances: 1
      users:
        indexer:
          - superuser
      enableMasterLoadBalancer: false
      enableReplicaLoadBalancer: false
      enableConnectionPooler: false # enable/disable connection pooler deployment
      enableReplicaConnectionPooler: false # set to enable connectionPooler for replica service
      databases:
        indexer: indexer
      postgresql:
        version: "14"
        parameters: {}
      volume:
        size: 20Gi
        storageClass: openebs-rawfile-localpv # change me to your desired storage class
      resources:
        requests:
          cpu: 100m
          memory: 2Gi
        limits:
          cpu: 500m
          memory: 4Gi
      patroni:
        initdb:
          encoding: "UTF8"
          locale: "C" # Improves performance and important for determinism
        pg_hba: # Allow nossl for indexer agent/service
          - local   all             all                                   trust
          - hostssl all             +zalandos    127.0.0.1/32       pam
          - host    all             all                127.0.0.1/32       md5
          - hostssl all             +zalandos    ::1/128            pam
          - host    all             all                ::1/128            md5
          - local   replication     standby                    trust
          - hostssl replication     standby all                md5
          - hostnossl all           all                all                md5
          - hostssl all             +zalandos    all                pam
          - hostssl all             all                all                md5
