bases:
  - ../helmfile.common.yaml

---

helmDefaults: &helmDefaults
{{ .Values.helmDefaults | toYaml | indent 2 }}

helmfiles:
  - path: git::https://github.com/graphops/launchpad-namespaces.git@ingress/helmfile.yaml?ref=ingress-stable/latest
    selectorsInherited: true
    values:
    - helmDefaults:
        <<: *helmDefaults
    - kubeVersion: {{ .Values.kubeVersion }}
      # ingress-nginx:
      #   values:
      #     your custom values go here